apiVersion: apps/v1
kind: Deployment
metadata:
  name: digittotext-deploy
  labels:
    app: digittotext-app
spec:
  selector:
    matchLabels:
      app: digittotext-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digittotext-app
    spec:
      containers:
        - name: digittotext-app
          image: digittotext:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000