apiVersion: v1
kind: Service
metadata:
  name: digittotext-service
  labels:
    app: digittotext-app
spec:
  selector:
    app: digittotext-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080