apiVersion: apps/v1
kind: Deployment
metadata:
  name: talk-deploy
  labels:
    app: talk-app
spec:
  selector:
    matchLabels:
      app: talk-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: talk-app
    spec:
      containers:
        - name: talk-app
          image: talk:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000