apiVersion: v1
kind: Service
metadata:
  name: vision-service
  labels:
    app: vision-app
spec:
  selector:
    app: vision-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer